name = "Create'a Colony PhantomVer"
author = "kilaXphantom"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "36a75ea8095323862ac7a7d81517c2e8bc8d69e6af4223a499580c0ba118f9ff"

[versions]
forge = "47.2.0"
minecraft = "1.20.1"
