name = "Create'a Colony PhantomVer"
author = "kilaXphantom"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "3395482222eabbc30aacf3dfe0a61bb2e326a64bc2efab3a8cfca251500cd279"

[versions]
forge = "47.2.0"
minecraft = "1.20.1"
