name = "Create'a Colony PhantomVer"
author = "kilaXphantom"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "81d393bf0217a867131e3641401243f68ca6cddbb3d399a0e5e44e194d819208"

[versions]
forge = "47.2.0"
minecraft = "1.20.1"
