name = "Create'a Colony PhantomVer"
author = "kilaXphantom"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "e466ab586eaa8b12262c90b55500118581325875c1399fc224b5679152d3164d"

[versions]
forge = "47.2.0"
minecraft = "1.20.1"
