name = "Create'a Colony PhantomVer"
author = "kilaXphantom"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "1e039933e8f5f1e6e63f484d09a686fc2e909b7e3e847a6ddfff78a176a2746e"

[versions]
forge = "47.2.0"
minecraft = "1.20.1"
