name = "Create'a Colony PhantomVer"
author = "kilaXphantom"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "e59f67b32e3f188dc0180cfc743632adb3d6671108e1c170d063983c68ce0b2f"

[versions]
forge = "47.2.0"
minecraft = "1.20.1"
