name = "Create'a Colony PhantomVer"
author = "kilaXphantom"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "e808db7e340b5927e1d6a0e65ed31f8801b340e1fb41a599f4339e90484ddf75"

[versions]
forge = "47.2.0"
minecraft = "1.20.1"
