name = "Create'a Colony PhantomVer"
author = "kilaXphantom"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "d685002bf8d771d6eb485d622fad03f188125cd24c73041a351a9acb02646734"

[versions]
forge = "47.2.0"
minecraft = "1.20.1"
