name = "Create'a Colony PhantomVer"
author = "kilaXphantom"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "004152e0cfe2cdf1da89ff4671529171f3c93b62e72d14ff31cced943621962d"

[versions]
forge = "47.2.0"
minecraft = "1.20.1"
