name = "Create'a Colony PhantomVer"
author = "kilaXphantom"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "393b54912889c481454cc8d2037924e268f04ad85d08353bff40f4ca302cc40f"

[versions]
forge = "47.2.0"
minecraft = "1.20.1"
