name = "Create'a Colony PhantomVer"
author = "kilaXphantom"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "84f8ad29d8e163a7a92b7bffcd3806b0390ec9446d983e829322adaed7fa3725"

[versions]
forge = "47.2.0"
minecraft = "1.20.1"
