name = "Create'a Colony PhantomVer"
author = "kilaXphantom"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "e0a6ea83576947f658380c41ff502e738dc83b93848f78ce533758461a144310"

[versions]
forge = "47.2.0"
minecraft = "1.20.1"
