name = "Create'a Colony PhantomVer"
author = "kilaXphantom"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "b2310fd6cf0b1f792c9e6325e307edaa50a1d31d9902eedf2dc1c7f364d63bc3"

[versions]
forge = "47.2.0"
minecraft = "1.20.1"
