name = "Create'a Colony PhantomVer"
author = "kilaXphantom"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "59f8755c36d0c8a0a31903c5a5a23ed64aee8e68ceeab07d8dc0f7b0f28ae953"

[versions]
forge = "47.2.0"
minecraft = "1.20.1"
