name = "Create'a Colony PhantomVer"
author = "kilaXphantom"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "30f134ca519269c24c38bb2a9b36aff2fa824438a5beaaf61005c73a0dc26048"

[versions]
forge = "47.2.0"
minecraft = "1.20.1"
