name = "Create'a Colony PhantomVer"
author = "kilaXphantom"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "d454142b0286a6fc38e357efd47135204d045a28cba37a6386f6041e81d73178"

[versions]
forge = "47.2.0"
minecraft = "1.20.1"
