name = "Create'a Colony PhantomVer"
author = "kilaXphantom"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "fefc270bda220d9ea77f3ee69141d05791c0a5ef43079cf635b32355a7d1acf8"

[versions]
forge = "47.2.0"
minecraft = "1.20.1"
