name = "Create'a Colony PhantomVer"
author = "kilaXphantom"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "2d70188c59000c14dc59682181ec87b5f246e09ccf8c309fccbd79d2c77a08dc"

[versions]
forge = "47.2.0"
minecraft = "1.20.1"
