name = "Create'a Colony PhantomVer"
author = "kilaXphantom"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "7ef47657cbdcc869083bce5e8bf22a5801cf23670f21ddc335ad4025a5b4bc9c"

[versions]
forge = "47.2.0"
minecraft = "1.20.1"
