name = "Create'a Colony PhantomVer"
author = "kilaXphantom"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "e965b588e3cc9f8b3dcd1ca91c015b21270ebb8786e04d62786ae128cd0028c8"

[versions]
forge = "47.2.0"
minecraft = "1.20.1"
