name = "Create'a Colony PhantomVer"
author = "kilaXphantom"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "63c4133b2f13fe5a5513846c79ef53afdc3d1cd4d15d991db1abee53a11688f1"

[versions]
forge = "47.2.0"
minecraft = "1.20.1"
