name = "Create'a Colony PhantomVer"
author = "kilaXphantom"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "fabc9cb65f90e56bb2d825351e72cb69fff72b158443599811ab2732f68cecdc"

[versions]
forge = "47.2.0"
minecraft = "1.20.1"
