name = "Create'a Colony PhantomVer"
author = "kilaXphantom"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "b7e33853159f400075d9cc56b96d98315738cbaf19cdb8cdcf4d1b24e3295c45"

[versions]
forge = "47.2.0"
minecraft = "1.20.1"
