name = "Create'a Colony PhantomVer"
author = "kilaXphantom"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "90822e1f529e8ab50116deb374ced3d0cc35e1b4070a8437e5a49e82e250eb63"

[versions]
forge = "47.2.0"
minecraft = "1.20.1"
