name = "Create'a Colony PhantomVer"
author = "kilaXphantom"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "5ac601104d59637c7b5ef6e17d97e6aa741af281178dbabc539e560991e3815f"

[versions]
forge = "47.2.0"
minecraft = "1.20.1"
