name = "Create'a Colony PhantomVer"
author = "kilaXphantom"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "6a72b877c995a657627157c9e2243be20019250ab86ee520862028df87d0ac0b"

[versions]
forge = "47.2.0"
minecraft = "1.20.1"
