name = "Create'a Colony PhantomVer"
author = "kilaXphantom"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "4f14a2d0aab8a5b7f2adc07373ab5706f5081ccce4831434dc0c8a433a42c2c4"

[versions]
forge = "47.2.0"
minecraft = "1.20.1"
