name = "Create'a Colony PhantomVer"
author = "kilaXphantom"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "d055f5774d642219e683e5aa3f26839985f20cc0fc8513d058cf5bbd2f188cfc"

[versions]
forge = "47.2.0"
minecraft = "1.20.1"
