name = "Create'a Colony PhantomVer"
author = "kilaXphantom"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "78fe12497f5b28e336f9838220f70703031be5748b3765b5958266cc16d0b88a"

[versions]
forge = "47.2.0"
minecraft = "1.20.1"
