name = "Create'a Colony PhantomVer"
author = "kilaXphantom"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "d5cbfaafd8ed4414e7b9882b24c48c3838aab138bff300f591ae003a7e533dd2"

[versions]
forge = "47.2.0"
minecraft = "1.20.1"
