name = "Create'a Colony PhantomVer"
author = "kilaXphantom"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "7c5d281f0956ee7a473d96ee8108ffefd68d6935e9472b8e50ac94521e3150b6"

[versions]
forge = "47.2.0"
minecraft = "1.20.1"
