name = "Create'a Colony PhantomVer"
author = "kilaXphantom"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "5f8fd0468989eee4d079954e22ad8dd3a1df1460a4cae43497c5533c952b52c1"

[versions]
forge = "47.2.0"
minecraft = "1.20.1"
