name = "Create'a Colony PhantomVer"
author = "kilaXphantom"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "ae97c8793378967204d17792fa5bfadfea710f1b10397d3deb620c212dd3c9f7"

[versions]
forge = "47.2.0"
minecraft = "1.20.1"
