name = "Create'a Colony PhantomVer"
author = "kilaXphantom"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "14527c3adc1f2679a6b83358721656dd68870400c88d6cf8e477f6b638f72593"

[versions]
forge = "47.2.0"
minecraft = "1.20.1"
