name = "Create'a Colony PhantomVer"
author = "kilaXphantom"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "4c09b09b8d5bf5c6217cba0f9ccf3070fa8bb184182ad14cbad604acd96ec980"

[versions]
forge = "47.2.0"
minecraft = "1.20.1"
