name = "Create'a Colony PhantomVer"
author = "kilaXphantom"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "84a9aacfcdb8d2376f94e0cc23b4390957b78078ef5952fbaee1a8a77034ae8d"

[versions]
forge = "47.2.0"
minecraft = "1.20.1"
