name = "Create'a Colony PhantomVer"
author = "kilaXphantom"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "2de3fe19d34e11122641dbb861b3edeac6d996a7fd8b6239ba1445428e89d1ad"

[versions]
forge = "47.2.0"
minecraft = "1.20.1"
