name = "Create'a Colony PhantomVer"
author = "kilaXphantom"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "bb686dab50d782f5ca37cdc7b65c3fc57e1301270385b3b53d9dac8118f95546"

[versions]
forge = "47.2.0"
minecraft = "1.20.1"
