name = "Create'a Colony PhantomVer"
author = "kilaXphantom"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "ee07f8e9d6de85cc16670de49fdb734bc50dd772471d77ad59d8d44676f52fda"

[versions]
forge = "47.2.0"
minecraft = "1.20.1"
