name = "Create'a Colony PhantomVer"
author = "kilaXphantom"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "9cd3740c86f608f44fc69ad32084cb4af23f90a6199c24d06e06b70e5d6972d4"

[versions]
forge = "47.2.0"
minecraft = "1.20.1"
