name = "Create'a Colony PhantomVer"
author = "kilaXphantom"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "d1fb93d142d5fab7f7e6998d786d35b595b123d62860c49a781bbc7c62ce076d"

[versions]
forge = "47.2.0"
minecraft = "1.20.1"
