name = "Create'a Colony PhantomVer"
author = "kilaXphantom"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "700ccc4df7fd493aaab75b381a43dbf43df73bd1da1f51f61480b0b2b9e4a9c3"

[versions]
forge = "47.2.0"
minecraft = "1.20.1"
