name = "Create'a Colony PhantomVer"
author = "kilaXphantom"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "cdea978468fcc69f059e163ece197e06a80c17897a6193b96292896f87529db4"

[versions]
forge = "47.2.0"
minecraft = "1.20.1"
