name = "Create'a Colony PhantomVer"
author = "kilaXphantom"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "ddfceeb99c036123536839c3be36f230fbde3008a62547d6d8f634e1a75036f8"

[versions]
forge = "47.2.0"
minecraft = "1.20.1"
