name = "Create'a Colony PhantomVer"
author = "kilaXphantom"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "35d7127ae163b4b37b299879f122ef430f7963bf7f544c64701217896e10ca98"

[versions]
forge = "47.2.0"
minecraft = "1.20.1"
