name = "Create'a Colony PhantomVer"
author = "kilaXphantom"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "47f41a820d15a9209f2402eef43b4f1e0b481912beac3bbe771711a43283e734"

[versions]
forge = "47.2.0"
minecraft = "1.20.1"
