name = "Create'a Colony PhantomVer"
author = "kilaXphantom"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "394bc7c54e72ee9840950c05ed151864c20a434d978a5d6da35cca64f7bb3837"

[versions]
forge = "47.2.0"
minecraft = "1.20.1"
