name = "Create'a Colony PhantomVer"
author = "kilaXphantom"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "7317023ba94d2934ecd77be01e1b5ea564d1610d8deade0fb43c1315dfcc9805"

[versions]
forge = "47.2.0"
minecraft = "1.20.1"
