name = "Create'a Colony PhantomVer"
author = "kilaXphantom"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "f6fd70023b88cce782117e98f2e470e5e3b9d02d612e18a80a254e183a051638"

[versions]
forge = "47.2.0"
minecraft = "1.20.1"
