name = "Create'a Colony PhantomVer"
author = "kilaXphantom"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "65bb891f805bffb8166034d0294da6154be3cdee4564564b70ac0f627159e6b4"

[versions]
forge = "47.2.0"
minecraft = "1.20.1"
