name = "Create'a Colony PhantomVer"
author = "kilaXphantom"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "eee8e0d344720a0bd37da19c90f43b5318fe5c18212df2b04c07583e5e0ba99d"

[versions]
forge = "47.2.0"
minecraft = "1.20.1"
