name = "Create'a Colony PhantomVer"
author = "kilaXphantom"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "b597a40d28f4108b292e7625c0b53f52eb0c28b69230e5c6ef3c185b0bc5ac1f"

[versions]
forge = "47.2.0"
minecraft = "1.20.1"
