name = "Create'a Colony PhantomVer"
author = "kilaXphantom"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "39a261acbfd0ee12ca141cb3834ef9a47511759ba0efacef9ea4d350c6321b6b"

[versions]
forge = "47.2.0"
minecraft = "1.20.1"
