name = "Create'a Colony PhantomVer"
author = "kilaXphantom"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "5f081655ad4363ec6f724babe841a028f61d937297083ddea9b6c9e2ae806465"

[versions]
forge = "47.2.0"
minecraft = "1.20.1"
