name = "Create'a Colony PhantomVer"
author = "kilaXphantom"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "0acbb776faec0ae832781fc198c6b97e1f66a9f7cbae61eaa387508be6f325d3"

[versions]
forge = "47.2.0"
minecraft = "1.20.1"
