name = "Create'a Colony PhantomVer"
author = "kilaXphantom"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "2266e600b986f6f7802a91c8bc29ca1aba4da45c0d6bb25f5677e077b3020701"

[versions]
forge = "47.2.0"
minecraft = "1.20.1"
