name = "Create'a Colony PhantomVer"
author = "kilaXphantom"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "2db42640ed985c1a5fca6d2836a5624a912eff907f4ff5ca093f28e9dec64aad"

[versions]
forge = "47.2.0"
minecraft = "1.20.1"
