name = "Create'a Colony PhantomVer"
author = "kilaXphantom"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "5ffd54fec561e800b8b1b729be926dd54a9815fee326693d5ea69a11b72a6dab"

[versions]
forge = "47.2.0"
minecraft = "1.20.1"
