name = "Create'a Colony PhantomVer"
author = "kilaXphantom"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "b73485425d502b06650c169aee408012b8c93da6b582b489ab020f44b4b7eb84"

[versions]
forge = "47.2.0"
minecraft = "1.20.1"
