name = "Create'a Colony PhantomVer"
author = "kilaXphantom"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "43ec75a22c887a9e627f92242fa2e47fa4aa53aad3d60455f1389fa6fc134777"

[versions]
forge = "47.2.0"
minecraft = "1.20.1"
