name = "Create'a Colony PhantomVer"
author = "kilaXphantom"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "e2bcb912bef135c5e2a8c2d5c50d0514f133fd29d9d2843137908bb2a97acd1f"

[versions]
forge = "47.2.0"
minecraft = "1.20.1"
