name = "Create'a Colony PhantomVer"
author = "kilaXphantom"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "cb322ea9b49b6e6d5990da6bcb54221ec09af0eb68b4a15cdeaedf999b0319dc"

[versions]
forge = "47.2.0"
minecraft = "1.20.1"
