name = "Create'a Colony PhantomVer"
author = "kilaXphantom"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "053e36f25c81ed92bc55df20847d119339bb5054fcde79eb88a72bbdf573d9dd"

[versions]
forge = "47.2.0"
minecraft = "1.20.1"
