name = "Create'a Colony PhantomVer"
author = "kilaXphantom"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "e6e683dceedbe57683fb3a21fd647f0cab58c257f2dbe4b507db8f171c17c1de"

[versions]
forge = "47.2.0"
minecraft = "1.20.1"
