name = "Create'a Colony PhantomVer"
author = "kilaXphantom"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "58d09e5fcde0929a911c7e96a09c9934fa8fb6189ab593c01be63e60c0bbb138"

[versions]
forge = "47.2.0"
minecraft = "1.20.1"
