name = "Create'a Colony PhantomVer"
author = "kilaXphantom"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "5af7ab6915fdc0edafe1b4b3607b2e0035d473fdf49bbb6f36a76e7094aafee8"

[versions]
forge = "47.2.0"
minecraft = "1.20.1"
