name = "Create'a Colony PhantomVer"
author = "kilaXphantom"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "51406aea606cc25147e1e0ac483dd0ae58e59d2e4e9a06ffe960df1e24c1f06b"

[versions]
forge = "47.2.0"
minecraft = "1.20.1"
