name = "Create'a Colony PhantomVer"
author = "kilaXphantom"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "c1ed6a1f35663ca80ea6ac4023bff80cc091ea4e54d55ff5295be115cc2cd136"

[versions]
forge = "47.2.0"
minecraft = "1.20.1"
