name = "Create'a Colony PhantomVer"
author = "kilaXphantom"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "512d9f102319c09b927195fb5632454bc8c225acf7f8c73cadc6590b02642298"

[versions]
forge = "47.2.0"
minecraft = "1.20.1"
